# Librairies

In [21]:
import math 
import copy
import numpy as np
import itertools

# Fonctions Utiles

### Calcul de distance 
        Calcul de distance entre deux points. 
        return a float

In [22]:
def calcul_distance(first_point_value, second_point_value):
    p0 = first_point_value
    p1 = second_point_value
    res = math.sqrt((p0[0] - p1[0])**2 + (p0[1] - p1[1])**2)
    return res

### Circuit length calculation
        Cycle: Order of the point in the alogorithm (index of the points)
        list_of_points: dict of all the point, the key is the label, the value is a tuple (x, y)
        return a float, a circuit length

In [23]:
def calcul_circuit(list_of_points, cycle):
    distance = 0
    i = 0
    for i in range (len(cycle)):
        "si i est a la derniere case de cycle"
        if (i == (len(cycle) - 1)):
            distance +=calcul_distance(list_of_points[cycle[i]], list_of_points[cycle[0]])
        else:
            distance +=calcul_distance(list_of_points[cycle[i]], list_of_points[cycle[i + 1]])
    return distance

### Algorithme de tri : MergeSort

In [24]:
def Fusion(tab1,tab2):
    n1=len(tab1) 
    n2= len(tab2)
    n= n1+n2
    j=1
    k=1
    tab=[0]*(n)
    
    for i in range(n):
        if((j<=n1) and ((k>n2) or (tab1[j-1][1]<=tab2[k-1][1]))):
            tab[i] = tab1[j-1]
            j=j+1
        else:
            tab[i]=tab2[k-1]
            k=k+1
    return tab

def MergeSort(tab):
    'declaration'
    longueurtab = len(tab)
    n1 = round(longueurtab/2)
    n2 = longueurtab-n1
    
    if (longueurtab==1):
        return tab
    else:
        'declarations'
        tab1=[0]*(n1)
        tab2=[0]*(n2)

        'traitement'
        for i in range(n1):
            tab1[i] =tab[i]
            
        for j in range(n2):
            tab2[j]=tab[n1+j]
            
        tab1 = MergeSort(tab1)
        tab2 = MergeSort(tab2)
        
        tab = Fusion(tab1, tab2)
    return tab

# Algorithme 1

    Implement the nearest_neighbor algorithm.
    first_point: label of the first point
    list_of_points: dict of all the point, the key is the label, the value is a tuple (x, y)
    return a list of point to visit, starting from first_point.

In [25]:
def nearest_neighbor_algorithm(first_point, list_of_points):
    p0 = list_of_points[first_point]
    unvisited = copy.copy(list_of_points)
    del unvisited[first_point]
    visited = list()
    visited.append(first_point)
    p = p0
    while len(unvisited) != 0 :
        res = [0]*(len(unvisited))
        i = 0
        for point in unvisited:
            "on recupere la liste des distance "
            "res[i] = (point en question, distance par rapport a p)"
            res[i] = (point,  calcul_distance(p, unvisited[point]),unvisited[point])
            i=i+1
        "tri sur le tuple les distance"
        res = MergeSort(res)
        p = res[0]
        visited.append(p[0])
        del unvisited[p[0]]
    return list(visited)

# Algorithme 2

Matrice qui contient l'index d'un point et les distances qui séparent ce point des autres points.

[index, distancepoint1, distancepoint2]

In [130]:
def get_MatriceDistance(first_point, list_of_points, matrice_distance, longueur):
    #declaration
    matrice_point=[0]*(longueur) #matrice des coordonnees des points, cela sert a la suppression
    
    pointReference=list_of_points[first_point]
    points = copy.copy(list_of_points)
   
    del points[first_point] #on supprime le point de reference du tableau de points
    matrice_distance[0][0] = first_point
    
    #Remplissage de la matrice des distances 
    for cpt_ligne in range(longueur): # print(matrice_point)
        matrice_point[0]= list_of_points[cpt_ligne]
        matrice_distance[cpt_ligne][0] = cpt_ligne
        cpt_colonne = 1
        for index_point in points:
            matrice_distance[cpt_ligne][cpt_colonne] = (calcul_distance(pointReference, points[index_point]))
            matrice_point[cpt_colonne]= points[index_point]
            cpt_colonne = cpt_colonne + 1
        points[longueur+cpt_ligne]=pointReference
        pointReference=matrice_point[1]
        del points[cpt_ligne+1]
        
    return matrice_distance

        Implement a good algorithm to resolve the case.
        first_point: label of the first point
        list_of_points: dict of all the point, the key is the label, the value is a tuple (x, y)
        return a list of point to visit, starting from first_point.

In [163]:
def great_algorithm(first_point, list_of_points):

    #declaration
    longueur=len(list_of_points)
    matrice_distance = np.zeros((longueur,longueur))
    ArbrePoidsMin = np.zeros((longueur,2))
    distance_min = 100000
    index_point=0
    index_final =0
    points = list()
    
    matrice_distance = get_MatriceDistance(first_point, list_of_points, matrice_distance, longueur)
    
    "On détermine le point le plus eloigne du point de depart"
    distance_max=0
    for cpt_colonne in range(1,longueur):
        if(matrice_distance[first_point][cpt_colonne]>distance_max):
            index_point = first_point+cpt_colonne
            if(index_point >= longueur):
                    index_point = index_point - longueur
            distance_max= matrice_distance[first_point][cpt_colonne]
    
    "On part du point de départ on va jusqu'au point le+ eloigne avec ce point , puis on fait au plus proche"  
    points.append(first_point)
    points.append(index_point)

    
    while(len(points)!=longueur):
        distance_min = 100000
        index_min=0
        
        for cpt_colonne in range(1,longueur):
            
            index_min = index_point+cpt_colonne
            
            if(index_min >= longueur):
                    index_min = index_min - longueur

            if(len(points)==(longueur-1) and index_min not in points):
                index_final=index_min
                
            if(matrice_distance[index_point][cpt_colonne]<distance_min and index_min not in points):
                distance_min = matrice_distance[index_point][cpt_colonne]
                index_final=index_min
                
            
        points.append(index_final)
        index_point = index_final
    print(matrice_distance)
    """
    print(calcul_circuit(list_of_points,points))"""
    
    
    
    return list(points)

# Algorithme 3

        Implement an optimal algorithm. This solution is the best, but it is slow
        first_point: label of the first point
        list_of_points: dict of all the point, the key is the label, the value is a tuple (x, y)
        return a list of point to visit, starting from first_point.

In [132]:
def optimal_algorithm(first_point, list_of_points):
    distance_circuit = 10000
    
    "on copie la liste de points"
    circuit= copy.copy(list_of_points)
    
    "On retire le premier point de la permutation"
    del circuit[0]

    "calcul de toutes les possibilites de circuit "
    permutations=list(itertools.permutations(circuit)) 

    for circuit_permute in permutations:
        "on remet le premier point au circuit "
        circuit_permute=(first_point,) + circuit_permute 
        
        if(calcul_circuit(list_of_points,circuit_permute)<distance_circuit):
            distance_circuit =calcul_circuit(list_of_points,circuit_permute)
            circuitOptimal=circuit_permute

    return list(circuitOptimal)

# Tests

### Jeu de données 

In [29]:
def get_small_list_of_points():
    list_of_points = {
        0: (1, 3),
        1: (2, 5),
        2: (0, 6),
        3: (1, 7),
        4: (5, 1),
        5: (5, 5),
        6: (6, 3),
        7: (4, 4),
        8: (7, 0),
        9: (6, 6)
    }
    return list_of_points

In [30]:
def get_tricky_points():
    list_of_points = {
        0: (0, 0),
        1: (0, 1),
        2: (0, 3),
        3: (0, 11),
        4: (0, -21),
        5: (0, -5),
        6: (0, -1),
    }
    return list_of_points

### tests des fonctions utiles

In [31]:
def test_calcul_distance():
    a = (-3, -2)
    b = (5, 2)

    assert round(calcul_distance(a, b), 3) == 8.944

In [32]:
def test_calcul_min_circuit():
    a = (-3, -2)
    b = (5, 2)
    list_of_points = {'a': a, 'b': b}
    cycle = ['a', 'b']

    assert round(calcul_circuit(list_of_points, cycle), 3) == 17.889

In [33]:
def test_calcul_circuit():
    list_of_points = get_small_list_of_points()

    cycle = list(list_of_points.keys())
    distance = calcul_circuit(list_of_points, cycle)
    assert round(distance, 3) == 38.483

In [34]:
def test_return_sized():
    list_of_points = get_small_list_of_points()

    first_point = 0
    result = nearest_neighbor_algorithm(first_point, list_of_points)
    assert len(result) == 10
    assert result[0] == first_point

### tests des algorithmes 

In [149]:
def test_small_nearest_neighbor():
    list_of_points = get_small_list_of_points()
    first_point = 0
    result = nearest_neighbor_algorithm(first_point, list_of_points)
    print(result)
    print(calcul_circuit(list_of_points, result))

In [140]:
def test_small_better_algorithm():
    list_of_points = get_small_list_of_points()

    first_point = 0
    result = great_algorithm(first_point, list_of_points)
    print(result)
    print(calcul_circuit(list_of_points, result))
    assert len(result) == 10
    assert result[0] == first_point

In [155]:
def test_small_optimal_algorithm():
    list_of_points = get_small_list_of_points()

    first_point = 0
    result = optimal_algorithm(first_point, list_of_points)
    print(calcul_circuit(list_of_points, result))
    assert len(result) == 10
    assert result[0] == first_point
    circuit_cost = calcul_circuit(list_of_points, result)
    assert round(circuit_cost) <= 27
    assert round(circuit_cost, 2) == 24.75
    print(result)
    assert result == [0, 2, 3, 1, 7, 5, 9, 6, 8, 4]

In [142]:
def test_tricky_nearest_neighbor():
    list_of_points = get_tricky_points()

    first_point = 0
    result = nearest_neighbor_algorithm(first_point, list_of_points)
    print(result)
    print(calcul_circuit(list_of_points, result))
    assert len(result) == 7
    assert result[0] == first_point
    assert round(calcul_circuit(list_of_points, result)) <= 80

In [143]:
def test_tricky_better_algorithm():
    list_of_points = get_tricky_points()

    first_point = 0
    result = great_algorithm(first_point, list_of_points)
    print(result)
    print(calcul_circuit(list_of_points, result))
    assert len(result) == 7
    assert result[0] == first_point
    assert round(calcul_circuit(list_of_points, result)) < 80

In [144]:
def test_tricky_optimal_algorithm():
    list_of_points = get_tricky_points()

    first_point = 0
    result = optimal_algorithm(first_point, list_of_points)
    print(result)
    print(calcul_circuit(list_of_points, result))
    assert len(result) == 7
    assert result[0] == first_point
    assert round(calcul_circuit(list_of_points, result)) == 64

In [166]:
test_small_nearest_neighbor()
test_small_better_algorithm()
test_small_optimal_algorithm()

[0, 1, 7, 6, 4, 8, 9, 5, 3, 2]
27.725943157711317
[[0.         2.23606798 3.16227766 4.         4.47213595 4.47213595
  5.         3.16227766 6.70820393 5.83095189]
 [1.         2.23606798 2.23606798 5.         3.         4.47213595
  2.23606798 7.07106781 4.12310563 2.23606798]
 [2.         1.41421356 7.07106781 5.09901951 6.70820393 4.47213595
  9.21954446 6.         3.16227766 2.23606798]
 [3.         7.21110255 4.47213595 6.40312424 4.24264069 9.21954446
  5.09901951 4.         2.23606798 1.41421356]
 [4.         4.         2.23606798 3.16227766 2.23606798 5.09901951
  4.47213595 5.         7.07106781 7.21110255]
 [5.         2.23606798 1.41421356 5.38516481 1.41421356 4.47213595
  3.         5.09901951 4.47213595 4.        ]
 [6.         2.23606798 3.16227766 3.         5.         4.47213595
  6.70820393 6.40312424 2.23606798 2.23606798]
 [7.         5.         2.82842712 3.16227766 2.23606798 4.47213595
  4.24264069 3.16227766 1.41421356 2.23606798]
 [8.         6.08276253 6.7082

In [165]:
test_tricky_nearest_neighbor()
test_tricky_better_algorithm()
test_tricky_optimal_algorithm()

[0, 1, 2, 6, 3, 5, 4]
72.0
[[ 0.  1.  3. 11. 21.  5.  1.]
 [ 1.  2. 10. 22.  6.  2.  1.]
 [ 2.  8. 24.  8.  4.  3.  2.]
 [ 3. 32. 16. 12. 11. 10.  8.]
 [ 4. 16. 20. 21. 22. 24. 32.]
 [ 5.  4.  5.  6.  8. 16. 16.]
 [ 6.  1.  2.  4. 12. 20.  4.]]
[0, 4, 5, 6, 1, 2, 3]
64.0
[0, 1, 2, 3, 4, 5, 6]
64.0
