In [3]:
import math 
import copy
import numpy as np


In [4]:
def calcul_distance(first_point_value, second_point_value):
    p0 = first_point_value
    p1 = second_point_value
    res = math.sqrt((p0[0] - p1[0])**2 + (p0[1] - p1[1])**2)
    return res

In [5]:
def calcul_circuit(list_of_points, cycle):
    """
        Circuit length calculation
        Cycle: Order of the point in the alogorithm (name of the points)
        list_of_points: dict of all the point, the key is the label, the value is a tuple (x, y)
        return a float, a circuit length
    """
    distance = 0
    i = 0
    for i in range (len(cycle)):
        "si i est a la derniere case de cycle"
        if (i == (len(cycle) - 1)):
            distance +=calcul_distance(list_of_points[cycle[i]], list_of_points[cycle[0]])
        else:
            distance +=calcul_distance(list_of_points[cycle[i]], list_of_points[cycle[i + 1]])
        return distance


In [6]:
#tri efficace (Quick sort)
def pivot(tab,cpt_debut,cpt_fin): 
    index = cpt_debut-1
    pivot = tab[cpt_fin] 
    value=0
    for i in range(cpt_fin , cpt_debut):
        if   tab[i] <= pivot:       
            index = index+1 
            value = tab[i]
            tab[i]= tab[index]
            tab[index]=value
    value= tab[index+1]
    tab[index+1]=tab[cpt_fin]
    tab[cpt_fin] = tab[index+1] 
    return (index+1) 
  
# Function to do Quick sort 
def quickSort(tab,cpt_debut,cpt_fin): 
    if (cpt_debut < cpt_fin): 
        v_pivot = pivot(tab,cpt_debut,cpt_fin)
        quickSort(tab,cpt_debut,v_pivot-1) 
        quickSort(tab,v_pivot+1+1,cpt_fin)

In [74]:
def great_algorithm(first_point, list_of_points):
    """
        Implement a good algorithm to resolve the case.
        first_point: label of the first point
        list_of_points: dict of all the point, the key is the label, the value is a tuple (x, y)
        return a list of point to visit, starting from first_point.
    """
    n=len(list_of_points)
    mat = np.zeros((n,n))
    print(mat)
    p=list_of_points[first_point]
    points = copy.copy(list_of_points)
   
    del points[first_point]
    
    i=0

    mat[i][i] = first_point

    #for j in range(0,len(list_of_points)):
    for point in points:
        print(i)
        print(point-i)
        print(points[point])
        print(p)
        mat[i][point-i] = (points[point],calcul_distance(p, points[point]))
        print(mat)
    points[n+i]=p
    p=mat[i][i+1][0]
    del points[i+1]
    i=i+1

    return list(list_of_points.keys())

In [75]:
def get_small_list_of_points():
    list_of_points = {
        0: (1, 3),
        1: (2, 5),
        2: (0, 6),
        3: (1, 7),
        4: (5, 1),
        5: (5, 5),
        6: (6, 3),
        7: (4, 4),
        8: (7, 0),
        9: (6, 6)
    }
    return list_of_points
great_algorithm(0,get_small_list_of_points())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
0
1
(2, 5)
(1, 3)


ValueError: setting an array element with a sequence.